// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAAxPGh-lHy0yKM5jtu9SqEPc5XSEnGlE',
    appId: '1:42456755252:web:9d4a3731e0a5d9a4e56e61',
    messagingSenderId: '42456755252',
    projectId: 'cameraapp-d841e',
    authDomain: 'cameraapp-d841e.firebaseapp.com',
    storageBucket: 'cameraapp-d841e.appspot.com',
    measurementId: 'G-7VV07TLJL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfhmxYMtkDqkpl3qHd0wYH1cee2M8vbYY',
    appId: '1:42456755252:android:84facf44163714dfe56e61',
    messagingSenderId: '42456755252',
    projectId: 'cameraapp-d841e',
    storageBucket: 'cameraapp-d841e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkUTPLkP2c_J9-2lARTkYaPs6SAciTYlI',
    appId: '1:42456755252:ios:f4b354477c12a2dee56e61',
    messagingSenderId: '42456755252',
    projectId: 'cameraapp-d841e',
    storageBucket: 'cameraapp-d841e.appspot.com',
    iosClientId: '42456755252-p6pu46cmvrluuj5npmk6n44tjkqjfgnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cameraapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkUTPLkP2c_J9-2lARTkYaPs6SAciTYlI',
    appId: '1:42456755252:ios:f4b354477c12a2dee56e61',
    messagingSenderId: '42456755252',
    projectId: 'cameraapp-d841e',
    storageBucket: 'cameraapp-d841e.appspot.com',
    iosClientId: '42456755252-p6pu46cmvrluuj5npmk6n44tjkqjfgnb.apps.googleusercontent.com',
    iosBundleId: 'com.example.cameraapp',
  );
}
